#static code analysis by sonarqube
 steps:
 - name: 'maven:3.6.1-jdk-8'
   entrypoint: 'bash'
   args:
    - -c
    - |
      unset MAVEN_CONFIG \
      && echo "104.199.71.165 sonarqube.ct.blue.cdtapps.com" > /etc/hosts \
      && mvn sonar:sonar -q -Dsonar.login=d4bb060355dc5b069f5c9cc92ee1de41b5a688b7 \
      '-Dsonar.projectKey=healthcaredemo' \
      '-Dsonar.projectName=healthcaredemo' \
      '-Dsonar.host.url=https://sonarcloud.io' \
      '-Dsonar.qualitygate.wait=true' \
      'allow_failure: true'
   dir: 'store-webapp-sample/src/main/'
   id: 'sonarqube-analysis'
