 steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']
 - name: 'gcr.io/PROJECT_ID/sonar-scanner:latest'
   args:
   - '-Dsonar.host.url=https://sonarcloud.io'
   - '-Dsonar.login=d4bb060355dc5b069f5c9cc92ee1de41b5a688b7'
   - '-Dsonar.projectKey=healthcaredemo'
   - '-Dsonar.organization=csidemo'
   - '-Dsonar.sources=.'
 images: 
 - 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
 - 'gcr.io/$PROJECT_ID/sonar-scanner:4.6.0.2311'

 tags: ['cloud-builders-community']
